### PR TITLE
s3 client helper

### PR DESCRIPTION
**Pull request by terrywbrady**
Run `make-s3-creds.sh`

Use the output of this file as a helper for browsing an S3-compatible bucket.

### CODE REVIEW

**Review by ashleygould — COMMENTED** [review]
I think this script is too application specific to add to the uc3-aws-cli project.  This would be better installed by puppet directly to target hosts, as we do with most app scripts.

**Comment by terrywbrady** [comment]
@ashleygould , what repo would you recommend that I use for this script so that it can be deployed as you suggest?

**Comment by terrywbrady** [comment]
Alternatively, I could just post the script inline into mrt-doc-private since it should really only need to be run once per domain.

**Comment by terrywbrady** [comment]
@ashleygould and I chatted.  Instead of a script, I will create some documentation snippets to set temporary AWS credentials and put that in inline documentation.

**Pull request closed without merging**
